### ISSUE TITLE
String interpolation test failure

### ISSUE THREAD

**Issue by nk9** [nk9/just_sublime#16]
One of the string interpolation tests has started failing with the new v2 Python syntax.

```
Packages/Just/Syntax/tests/syntax_test_just.recipe_embeddings.just:6:16:

[meta.string.python
string.quoted.double.python]

does not match scope

[source.just
source.python.embedded.just
meta.function-call.arguments.python
meta.string.python
meta.interpolation.just
punctuation.section.interpolation.begin.just]
```

The test is [here](https://github.com/nk9/just_sublime/blob/df7752729e9dcf89cf85c6d714c3657e2e063d53/Syntax/tests/syntax_test_just.recipe_embeddings.just#L3):
```justfile
python3 *ARGS:
  #!/usr/bin/python3
 #^^^^^^^^^^^^^^^^^^ source.python.embedded.just comment.line.number-sign.python
  print("hello {{ ARGS }} world")
 #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ source.python.embedded.just
 #     ^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.function-call.arguments.python
 #      ^^^^^^^^^^^^^^^^^^^^^^^^ meta.string.python string.quoted.double.python
 #             ^^^^^^^^^^ meta.interpolation.just
```

<img width="389" alt="image" src="https://user-images.githubusercontent.com/3646730/234606314-83facfa6-f7f2-4403-9cde-1e1b79443b8f.png">

The issue is that the v1 Python syntax includes the `string.quoted.double.python` scope on the interpolation piece (`{{ ARGS }}`), whereas the new syntax doesn't. I just want to confirm that it's correct to remove `string.quoted.double.python` from this test @deathaxe.

**Comment by deathaxe** [comment]
Removing `string` scope from interpolations is intented and already applied to various (most?) default syntaxes.

Each string is therefore scoped `meta.string string` to maintain a scope (`meta.string` for the whole string including the interpolation part, while `string` is replaced by `meta.interpolation`.

The reason for doing that is simple: ST treats `string` scopes special in various ways which effects e.g. auto-completion and sometimes highlighting of identifiers within interpolations.
