### ISSUE TITLE
Incorrect syntax scope after setting

### ISSUE THREAD

**Issue by crazygolem** [nk9/just_sublime#19]
The syntax rules seem to not handle correctly the first assignment following a setting.

I tried to look into it and I have a hunch that it might be caused by something incorrect with the `settings-boolean` rule, but I'm not familiar enough with the syntax configuration to figure it out.

**Example**

```just
set positional-arguments

export ONE := "1"
export TWO := "02"

set export := false

THREE := "003"
FOUR := "0004"

set shell := ["python3", "-c"]

export FOO := "bar"
export HELLO := "world"
```

is highlighted as

![image](https://user-images.githubusercontent.com/433553/235750371-ca83ad75-dc4b-4c64-b8ee-ce62aac483f0.png)

**Comment by nk9** [comment]
Thanks very much for the report, I'll have a look.

**Comment by nk9** [comment]
This should be fixed now. Please download release 1.1.4 via PackageControl.

**Comment by crazygolem** [comment]
I confirm that this bug is resolved, thanks :+1:
